'use strict';
const key='crs-demo-v2';
const seed={students:[],teachers:[],courses:[],attendance:[],payments:[],grades:[]};
let db;try{db=JSON.parse(window.demoStorage.getItem(key))||JSON.parse(JSON.stringify(seed))}catch{db=JSON.parse(JSON.stringify(seed))}
try{const pending=JSON.parse(window.demoStorage.getItem('crs-preinscriptions-v2')||'[]');if(pending.length){for(const s of pending)if(!db.students.some(x=>x.id===s.id))db.students.push(s);window.demoStorage.setItem(key,JSON.stringify(db));window.demoStorage.removeItem('crs-preinscriptions-v2')}}catch{}
let role='admin',identity='',page='dashboard',search='';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const student=id=>db.students.find(s=>s.id===id);const course=id=>db.courses.find(c=>c.id===id);const teacher=id=>db.teachers.find(t=>t.id===id);
const money=n=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';const date=d=>new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric'});
const sections={dashboard:['◈','Tableau de bord'],students:['♙','Élèves'],teachers:['♧','Enseignants'],courses:['▦','Cours & planning'],attendance:['✓','Présences'],payments:['◇','Paiements'],grades:['▤','Notes & résultats']};
const visibleCourses=()=>db.courses.filter(c=>role==='admin'||(role==='teacher'?c.teacher===identity:c.group===student(identity)?.group));
const visibleStudents=()=>db.students.filter(s=>role==='admin'||(role==='student'?s.id===identity:visibleCourses().some(c=>c.group===s.group)));
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3000)}
function save(){try{window.demoStorage.setItem(key,JSON.stringify(db));return true}catch{toast('Stockage indisponible : les changements ne sont pas sauvegardés.');return false}}
function identityOptions(){const list=role==='teacher'?db.teachers:role==='student'?db.students:[];$('identity').hidden=!list.length;$('identity').innerHTML=list.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');identity=list[0]?.id||''}
function navigation(){let entries=Object.keys(sections).filter(x=>role==='admin'||!['teachers','students'].includes(x)&&!(role==='teacher'&&x==='payments'));$('nav').innerHTML=entries.map(x=>`<button data-page="${x}" class="${page===x?'active':''}"><span>${sections[x][0]}</span>${sections[x][1]}</button>`).join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.page;search='';render()})}
function table(headers,rows){return rows.length?`<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`:'<div class="empty">Aucune donnée à afficher.</div>'}
function person(s){return `<span class="avatar">${esc(s.name.split(' ').map(p=>p[0]).slice(0,2).join(''))}</span>${esc(s.name)}`}
function panel(title,subtitle,body){return `<div class="panel"><div class="panel-head"><div><h2>${title}</h2><p>${subtitle}</p></div></div>${body}</div>`}
function dashboard(){const students=visibleStudents(),courses=visibleCourses();const grades=db.grades.filter(g=>students.some(s=>s.id===g.student)&&courses.some(c=>c.id===g.course));const average=grades.length?(grades.reduce((s,g)=>s+Number(g.score),0)/grades.length).toFixed(1):'—';const payments=db.payments.filter(p=>students.some(s=>s.id===p.student));const future=courses.filter(c=>c.date>=new Date().toLocaleDateString('en-CA')).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const stats=role==='teacher'?[['Élèves accompagnés',students.length,'Dans vos groupes'],['Cours planifiés',courses.length,'Toutes les séances'],['Moyenne des notes',average+' / 20','Évaluations enregistrées'],['Présences saisies',db.attendance.filter(a=>courses.some(c=>c.id===a.course)).length,'Statuts renseignés']]:[['Élèves inscrits',students.length,role==='student'?'Votre dossier':'Tous les groupes'],['Cours planifiés',courses.length,'Toutes les séances'],['Encaissements simulés',money(payments.reduce((s,p)=>s+Number(p.amount),0)),'Démonstration · aucun argent réel'],['Moyenne des notes',average+' / 20','Évaluations enregistrées']];return `<div class="welcome"><div><h2>${role==='admin'?'Un nouvel élan pour la réussite.':'Bienvenue, '+esc((role==='teacher'?teacher(identity):student(identity))?.name||'')+'.'}</h2><p>${role==='admin'?'Organisez les cours, accompagnez les élèves et suivez leurs progrès.<br>Tout votre établissement dans un seul espace.':'Retrouvez vos cours et suivez les progrès, séance après séance.'}</p></div><div class="art">✧</div></div><div class="stats">${stats.map(s=>`<div class="stat"><span class="stat-label">${s[0]}</span><strong>${s[1]}</strong><small>${s[2]}</small></div>`).join('')}</div><div class="columns">${panel('Prochaines séances','Le planning des cours de renforcement',future.length?future.slice(0,5).map(c=>`<div class="lesson"><div class="lesson-time">${esc(c.time)}</div><div><strong>${esc(c.subject)}</strong><p>${date(c.date)} · ${esc(c.group)}</p><span class="badge">${esc(c.room)} · ${c.duration} min</span></div></div>`).join(''):'<div class="empty">Aucune séance à venir.</div>')}${panel(role==='student'?'Mon parcours':'Les groupes','Des cours adaptés à chaque niveau',[...new Set(students.map(s=>s.group))].map(g=>`<div class="lesson"><div><strong>${esc(g)}</strong><p>${students.filter(s=>s.group===g).length} élève(s) · ${courses.filter(c=>c.group===g).length} séance(s)</p></div></div>`).join('')+'<p class="helper">Les montants sont affichés en FCFA. Les paiements saisis constituent un suivi administratif, sans transaction en ligne.</p>')}</div>`}
const addLabels={students:'Inscrire un élève',teachers:'Ajouter un enseignant',courses:'Planifier un cours',payments:'Enregistrer un paiement',grades:'Ajouter une note'};
function canAdd(){return role==='admin'&&page!=='attendance'||role==='teacher'&&page==='grades'}
function rowsForPage(){let rows=[];if(page==='students')rows=db.students.filter(s=>(s.name+' '+s.group).toLowerCase().includes(search)).map(s=>`<tr><td>${person(s)}</td><td>${esc(s.class)}</td><td><span class="badge">${esc(s.centre||s.group)}</span></td><td>${esc(s.registrationStatus||'Inscrit (démo)')}</td><td>${actions(s.id)}</td></tr>`);if(page==='teachers')rows=db.teachers.filter(t=>(t.name+' '+t.subject).toLowerCase().includes(search)).map(t=>`<tr><td>${person(t)}</td><td>${esc(t.subject)}</td><td>${[...new Set(db.courses.filter(c=>c.teacher===t.id).map(c=>c.group))].map(g=>`<span class="assignment-tag">${esc(g)}</span>`).join('')||'À affecter'}</td><td>${db.courses.filter(c=>c.teacher===t.id).length} séance(s)</td><td>${actions(t.id)}</td></tr>`);if(page==='courses')rows=visibleCourses().filter(c=>(c.subject+' '+c.group).toLowerCase().includes(search)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(c=>`<tr><td><strong>${esc(c.subject)}</strong></td><td>${esc(c.group)}</td><td>${esc(teacher(c.teacher)?.name||'—')}</td><td>${date(c.date)} · ${esc(c.time)}</td><td>${esc(c.room)} · ${c.duration} min</td>${role==='admin'?`<td>${actions(c.id)}</td>`:''}</tr>`);if(page==='payments')rows=db.payments.filter(p=>visibleStudents().some(s=>s.id===p.student)&&(student(p.student)?.name+' '+p.period).toLowerCase().includes(search)).map(p=>`<tr><td>${esc(student(p.student)?.name)}</td><td>${esc(p.period)}</td><td>${money(p.amount)}</td><td>${date(p.date)}</td><td><span class="badge">Enregistré</span></td>${role==='admin'?`<td>${actions(p.id)}</td>`:''}</tr>`);if(page==='grades')rows=db.grades.filter(g=>visibleStudents().some(s=>s.id===g.student)&&visibleCourses().some(c=>c.id===g.course)&&(student(g.student)?.name+' '+g.label+' '+course(g.course)?.subject).toLowerCase().includes(search)).map(g=>`<tr><td>${esc(student(g.student)?.name)}</td><td>${esc(course(g.course)?.subject)}</td><td>${esc(g.label)}</td><td><span class="badge ${g.score<10?'orange':''}">${g.score} / 20</span></td>${role!=='student'?`<td>${actions(g.id)}</td>`:''}</tr>`);return rows}
function actions(id){return `<div class="row-actions"><button class="secondary" data-edit="${esc(id)}">Modifier</button><button class="secondary danger" data-delete="${esc(id)}">Supprimer</button></div>`}
function list(){let headers={students:['Élève','Classe','Centre / Groupe','Statut','Actions'],teachers:['Enseignant','Matière','Classes affectées','Cours','Actions'],courses:['Matière','Groupe','Enseignant','Date & heure','Lieu'],payments:['Élève','Période','Montant','Date','Statut'],grades:['Élève','Matière','Évaluation','Note']}[page].slice();if((page==='courses'||page==='payments')&&role==='admin'||page==='grades'&&role!=='student')headers.push('Actions');return `<div class="panel"><div class="toolbar"><input id="search" type="search" placeholder="Rechercher…" aria-label="Rechercher" value="${esc(search)}">${canAdd()?`<button class="primary" id="add">+ ${addLabels[page]}</button>`:''}</div><div id="table">${table(headers,rowsForPage())}</div>${page==='payments'?'<p class="helper">Journal des montants reçus. Aucun tarif dû ni solde impayé n’est calculé.</p>':''}</div>`}
let selectedCourse='';function attendance(){const courses=visibleCourses();if(!courses.some(c=>c.id===selectedCourse))selectedCourse=courses[0]?.id||'';const c=course(selectedCourse);const students=visibleStudents().filter(s=>s.group===c?.group);return `<div class="panel"><div class="filter"><label for="session">Séance</label><select id="session">${courses.map(c=>`<option value="${c.id}" ${c.id===selectedCourse?'selected':''}>${esc(c.subject)} · ${esc(c.group)} · ${date(c.date)} ${c.time}</option>`).join('')}</select></div>${table(['Élève','Statut'],students.map(s=>{const a=db.attendance.find(a=>a.student===s.id&&a.course===selectedCourse);return `<tr><td>${person(s)}</td><td>${role==='student'?esc(a?.status||'Non renseigné'):`<select data-attendance="${s.id}" aria-label="Présence de ${esc(s.name)}">${['Non renseigné','Présent','Absent','Retard','Excusé'].map(v=>`<option ${v===(a?.status||'Non renseigné')?'selected':''}>${v}</option>`).join('')}</select>`}</td></tr>`}))}<p class="helper">Chaque statut est enregistré dès sa sélection.</p></div>`}
function render(){navigation();$('title').textContent=sections[page][1];$('content').innerHTML=page==='dashboard'?dashboard():page==='attendance'?attendance():page==='assignments'?assignmentsPage():page==='statistics'?statisticsPage():list();if(typeof bindAnalytics==='function')bindAnalytics();if($('add'))$('add').onclick=()=>openForm();if($('search'))$('search').oninput=e=>{search=e.target.value.toLowerCase();const pos=e.target.selectionStart;render();$('search').focus();if(pos!==null&&$('search').type!=='search')$('search').setSelectionRange(pos,pos)};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));if($('session'))$('session').onchange=e=>{selectedCourse=e.target.value;render()};document.querySelectorAll('[data-attendance]').forEach(s=>s.onchange=()=>{db.attendance=db.attendance.filter(a=>!(a.student===s.dataset.attendance&&a.course===selectedCourse));if(s.value!=='Non renseigné')db.attendance.push({student:s.dataset.attendance,course:selectedCourse,status:s.value});save();toast('Présence enregistrée')})}
function field(name,label,type='text',options=null,value=''){return `<label for="f-${name}">${label}</label>${options?`<select id="f-${name}" name="${name}" required>${options.map(o=>`<option value="${esc(o[0])}" ${String(value)===String(o[0])?'selected':''}>${esc(o[1])}</option>`).join('')}</select>`:`<input id="f-${name}" name="${name}" type="${type}" required value="${esc(value)}" ${name==='score'?'min="0" max="20" step="0.5"':name==='amount'?'min="1" step="1"':name==='duration'?'min="15" max="480" step="15"':'maxlength="100"'}>`}`}
function openForm(id){const r=db[page].find(x=>x.id===id)||{};let fields='';const f=(n,l,t='text',opts=null,defaultValue='')=>field(n,l,t,opts,r[n]??defaultValue);if(page==='students')fields=f('name','Nom complet')+f('class','Classe')+f('group','Groupe')+f('registrationStatus','Statut','text',[['Inscrit (démo)','Inscrit (démo)'],['Préinscription démo','Préinscription démo']]);if(page==='teachers')fields=f('name','Nom complet')+f('subject','Matière');if(page==='courses'){if(!db.teachers.length||!db.students.length)return toast('Ajoutez un enseignant et un élève avant de planifier un cours.');fields=f('subject','Matière')+f('group','Groupe','text',[...new Set(db.students.map(s=>s.group))].map(g=>[g,g]))+f('teacher','Enseignant','text',db.teachers.map(t=>[t.id,t.name]))+f('date','Date','date')+f('time','Heure de début','time')+f('duration','Durée en minutes','number',null,60)+f('room','Salle')}
if(page==='payments'){if(!db.students.length)return toast('Inscrivez un élève avant de saisir un paiement.');fields=f('student','Élève','text',db.students.map(s=>[s.id,s.name]))+f('amount','Montant reçu (FCFA)','number')+f('period','Période concernée')+f('date','Date du paiement','date',null,new Date().toLocaleDateString('en-CA'))}
if(page==='grades'){if(!visibleCourses().length||!visibleStudents().length)return toast('Planifiez un cours avec des élèves avant de saisir une note.');fields=f('course','Cours','text',visibleCourses().map(c=>[c.id,`${c.subject} · ${c.group} · ${date(c.date)}`]))+f('student','Élève','text',visibleStudents().map(s=>[s.id,s.name]))+f('label','Nom de l’évaluation')+f('score','Note sur 20','number')}
$('modal-title').textContent=id?'Modifier le dossier':addLabels[page];$('fields').innerHTML=fields;$('error').textContent='';if(page==='grades'){const sync=()=>{const group=course($('f-course').value)?.group;const old=$('f-student').value;$('f-student').innerHTML=visibleStudents().filter(s=>s.group===group).map(s=>`<option value="${s.id}" ${s.id===old?'selected':''}>${esc(s.name)}</option>`).join('')};$('f-course').onchange=sync;sync()}
$('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));Object.keys(data).forEach(k=>data[k]=data[k].trim());if(Object.values(data).some(v=>!v)){return $('error').textContent='Veuillez renseigner tous les champs.'}for(const k of ['amount','score','duration'])if(k in data)data[k]=Number(data[k]);if(page==='grades'&&student(data.student)?.group!==course(data.course)?.group)return $('error').textContent='Cet élève ne fait pas partie du groupe de ce cours.';if(page==='courses'){const overlaps=db.courses.some(c=>{if(c.id===id||c.date!==data.date)return false;const mins=t=>Number(t.slice(0,2))*60+Number(t.slice(3));return (c.teacher===data.teacher||c.group===data.group||c.room.toLowerCase()===data.room.toLowerCase())&&mins(c.time)<mins(data.time)+data.duration&&mins(data.time)<mins(c.time)+c.duration});if(overlaps)return $('error').textContent='Créneau déjà occupé pour cet enseignant, ce groupe ou cette salle.'}data.id=id||window.createDemoID();if(id)db[page]=db[page].map(x=>x.id===id?{...x,...data}:x);else db[page].push(data);save();$('modal').close();identityOptionsPreserve();render();toast('Enregistrement effectué')};$('modal').showModal()}
function identityOptionsPreserve(){const old=identity;identityOptions();if([...$('identity').options].some(o=>o.value===old)){$('identity').value=old;identity=old}}
function remove(id){if(page==='students'&&(db.payments.some(p=>p.student===id)||db.grades.some(g=>g.student===id)||db.attendance.some(a=>a.student===id)))return toast('Cet élève possède des notes, paiements ou présences. Supprimez ces données avant son dossier.');if(page==='teachers'&&db.courses.some(c=>c.teacher===id))return toast('Cet enseignant est affecté à des cours. Modifiez les cours avant de le supprimer.');if(page==='courses'&&(db.grades.some(g=>g.course===id)||db.attendance.some(a=>a.course===id)))return toast('Ce cours possède des notes ou présences et doit être conservé.');if(!confirm('Supprimer cet enregistrement ?'))return;db[page]=db[page].filter(x=>x.id!==id);save();render();toast('Enregistrement supprimé')}
$('close').onclick=()=>$('modal').close();$('role').onchange=e=>{role=e.target.value;page='dashboard';identityOptions();render()};$('identity').onchange=e=>{identity=e.target.value;render()};identityOptions();
