"use strict";
const levels=[["6e",3500],["4e",4000],["3e",4500],["Seconde D – C",4500],["Première D – C",4500],["Terminale D – C",5000]];
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
let current=null,receipt=null;
const key='crs-demo-v2',pendingKey='crs-preinscriptions-v2';
function read(k,fallback){const raw=localStorage.getItem(k);return raw?JSON.parse(raw):fallback}
function load(){const db=read(key,null);if(db&&!['students','teachers','courses','attendance','payments','grades'].every(k=>Array.isArray(db[k])))throw Error('Données existantes illisibles. Elles ont été conservées.');return db}
function saveStudent(record){const db=load();if(db){db.students.push(record);localStorage.setItem(key,JSON.stringify(db))}else{const pending=read(pendingKey,[]);if(!Array.isArray(pending))throw Error('Données existantes illisibles.');pending.push(record);localStorage.setItem(pendingKey,JSON.stringify(pending))}}
function message(text){$('error').textContent=text}
function confirmed(){ $('registration-panel').hidden=true;$('confirmation').hidden=false;$('student-name').textContent=current.name;$('reference').textContent=current.id;$('summary-class').textContent=current.class;$('summary-centre').textContent=current.centre;$('amount').textContent=money(current.monthlyFee);$('paid').hidden=!receipt;$('pay').hidden=!!receipt;$('payment-note').hidden=!!receipt;if(receipt){$('receipt-reference').textContent=receipt.id;$('receipt-amount').textContent=money(receipt.amount)} }
$('class').innerHTML=levels.map(([name])=>`<option>${name}</option>`).join('');
function fee(){ $('fee').textContent=money(levels.find(([n])=>n===$('class').value)[1])+' / mois' }
$('class').onchange=fee;fee();
$('registration').onsubmit=e=>{e.preventDefault();message('');const data=new FormData(e.target),name=String(data.get('name')).trim(),guardian=String(data.get('guardian')).trim(),phone=String(data.get('phone')).trim(),subjects=data.getAll('subjects');if(!name)return message('Renseignez le nom de l’élève.');if(!guardian)return message('Renseignez le nom du responsable.');if(!/^[+0-9 ()-]{8,20}$/.test(phone))return message('Renseignez un numéro de téléphone valide.');if(!subjects.length)return message('Choisissez au moins une matière.');if(!$('consent').checked)return message('Confirmez que vous utilisez des données fictives pour la démonstration.');const record={id:crypto.randomUUID(),name,guardian,phone,subjects,class:data.get('class'),centre:data.get('centre'),group:data.get('class')+' · '+data.get('centre'),monthlyFee:levels.find(([n])=>n===data.get('class'))[1],registrationStatus:'Préinscription démo'};try{saveStudent(record);current=record;receipt=null;confirmed()}catch(err){message('Enregistrement impossible : '+err.message)}};
$('pay').onclick=()=>{$('payment-error').textContent='';$('payment-form').reset();$('payment-amount').textContent=money(current.monthlyFee);$('payment-phone').value=current.phone;$('payment-dialog').showModal()};
$('cancel-payment').onclick=()=>{$('payment-dialog').close();$('payment-status').textContent='Paiement annulé. Votre inscription est conservée. Vous pouvez payer plus tard.'};
$('payment-dialog').addEventListener('cancel',()=>{$('payment-status').textContent='Paiement annulé. Votre inscription est conservée.'});
$('payment-form').onsubmit=e=>{e.preventDefault();$('payment-error').textContent='';if(receipt)return;if(!/^[+0-9 ()-]{8,20}$/.test($('payment-phone').value.trim())){$('payment-error').textContent='Indiquez un numéro Mobile Money valide.';return}if($('outcome').value==='failure'){$('payment-error').textContent='Échec simulé : paiement refusé. Aucun montant enregistré. Vérifiez le numéro et réessayez.';return}const button=$('confirm-payment');button.disabled=true;try{let db=load();if(!db){db={students:read(pendingKey,[]),teachers:[],courses:[],attendance:[],payments:[],grades:[]};if(!Array.isArray(db.students))throw Error('Données existantes illisibles.')}if(!db.students.some(s=>s.id===current.id))throw Error('Dossier introuvable.');const period=new Date().toLocaleDateString('fr-FR',{month:'long',year:'numeric'});const previous=db.payments.find(p=>p.student===current.id&&p.period===period&&p.demoCheckout);const payment=previous||{id:'DEMO-'+crypto.randomUUID(),student:current.id,amount:current.monthlyFee,date:new Date().toLocaleDateString('en-CA'),period,method:$('method').value,demoCheckout:true,sandbox:true};if(!previous)db.payments.push(payment);localStorage.setItem(key,JSON.stringify(db));localStorage.removeItem(pendingKey);receipt=payment;$('payment-dialog').close();$('payment-status').textContent='';confirmed()}catch(err){$('payment-error').textContent='Paiement non enregistré : '+err.message}finally{button.disabled=false}};
$('new-registration').onclick=()=>{current=null;receipt=null;$('registration').reset();fee();$('confirmation').hidden=true;$('registration-panel').hidden=false;$('payment-status').textContent='';message('');window.scrollTo(0,0)};
