#!/usr/bin/env node
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname,'..');
const read = file => fs.readFileSync(path.join(root,file),'utf8');
function replaceOnce(source,from,to,label) {
  const at = source.indexOf(from);
  if (at < 0 || source.indexOf(from,at + from.length) !== -1) throw new Error('Transformation de démonstration introuvable ou ambiguë : '+label);
  return source.slice(0,at)+to+source.slice(at+from.length);
}
let offline = read('public/offline.js');
offline = replaceOnce(offline,"indexedDB.open('comptoir-local', 1)","indexedDB.open('comptoir-demo-cache', 1)",'namespace du cache');
offline = replaceOnce(offline,'export const local =','const local =','adaptateur de stockage incorporé');
let app = read('public/script.js');
app = replaceOnce(app,"import { local } from './offline.js';\n",'','import du cache');
const apiStart = app.indexOf('  async function api(path, data');
const apiEnd = app.indexOf('  async function refresh() {',apiStart);
if(apiStart < 0 || apiEnd < 0) throw new Error('Fonction API à adapter introuvable.');
app = app.slice(0,apiStart)+'  async function api(path, data, method = data ? \'POST\' : \'GET\') {\n    return window.ComptoirDemoAPI.request(path,data,method);\n  }\n'+app.slice(apiEnd);
app = replaceOnce(app,"fetch('/upload',{method:'POST',body})",'window.ComptoirDemoAPI.uploadResponse(body)','envoi des photos local');
app = replaceOnce(app,"    if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});\n",'','service worker');
app = app.replaceAll('navigator.onLine','true');
app = replaceOnce(app,"window.addEventListener('offline',()=>{cached=true;updateSync();});","window.addEventListener('offline',()=>updateSync());",'état local indépendant du réseau');
app = replaceOnce(app,"pending.length?`${pending.length} en attente`:'À jour'","pending.length?`${pending.length} en attente`:'Enregistré localement'",'statut du stockage');
app = app.replaceAll('Synchronisation…','Enregistrement…');
app = app.replaceAll('Bénéfice brut réalisé','Bénéfice brut estimé');
app = app.replaceAll('Connectez-vous pour suivre votre commerce.','Choisissez un compte pour explorer cette démonstration.');
app = app.replaceAll('Accès protégé · Données conservées sur votre serveur','Comptes et rôles simulés · Données stockées sur cet appareil');
app = app.replaceAll('Données du serveur','Données sur cet appareil');
app = app.replaceAll('Consultation et saisies disponibles hors ligne','Démonstration autonome, disponible sans connexion');
app = app.replaceAll('Connexion requise pour l’envoi.','Photo enregistrée sur cet appareil.');
app = app.replaceAll('Les rôles sont contrôlés côté serveur : administrateur, caissier et agent d’inventaire.','Les rôles sont simulés dans cette démonstration : administrateur, caissier et agent d’inventaire.');
app = app.replaceAll('Ce fichier ne contient ni comptes, ni fichiers image ; il ne remplace pas une sauvegarde complète de la base.','Ce fichier inclut les photos du catalogue, mais aucun compte ni mot de passe.');
app = app.replaceAll('Pour une sauvegarde complète : base SQLite et dossier uploads. L’automatisation cloud reste à déployer.','Le fichier HTML contient les données fictives initiales. Vos modifications restent dans le stockage du navigateur ; exportez-les avant de changer d’appareil.');
app = app.replaceAll('Votre dernier état est conservé sur cet appareil. Les saisies hors ligne sont mises en attente, puis validées par le serveur à la reconnexion.','Vos opérations sont validées et enregistrées sur cet appareil, sans connexion et sans serveur.');
app = app.replaceAll('Cette version synchronise avec le serveur local. La connexion à un hébergement cloud sera ajoutée à l’étape suivante. Évitez les appareils partagés pour les données sensibles hors ligne.','Cette démonstration ne synchronise pas vos données avec un autre appareil. Utilisez uniquement des données fictives.');
app = app.replaceAll('Hors ligne & synchronisation','Stockage sur cet appareil');
app = app.replaceAll('Ces saisies seront validées par le serveur, sans double enregistrement.','Ces saisies seront validées par le moteur de démonstration, sans double enregistrement.');
app = app.replaceAll('Toutes vos saisies sont synchronisées','Toutes vos saisies sont enregistrées localement');
app = app.replaceAll('Synchroniser maintenant','Vérifier les enregistrements');
app = app.replaceAll('Instantané JSON téléchargé (sans images ni comptes).','Instantané JSON téléchargé, photos incluses, sans comptes.');
app = app.replaceAll('Synchroniser et voir les saisies en attente','Vérifier les enregistrements locaux');
app = app.replaceAll('Saisie conservée sur cet appareil, en attente de validation.','Saisie conservée sur cet appareil, en attente de validation locale.');
app = app.replaceAll('Connexion au serveur rétablie.','Stockage local disponible.');
app = app.replaceAll('href="/"','href="#"');
const core = read('demo/demo-core.js');
const reversals = read('lib/reversals.js');
const backups = read('demo/demo-backups.js');
const browser = read('demo/demo-browser.js');
const seed = JSON.parse(read('demo/seed.json'));
if(!Array.isArray(seed._demoUsers) || seed._demoUsers.length !== 3 || seed._demoUsers.some(user => 'password' in user || 'passwordHash' in user)) throw new Error('Trois comptes publics, sans mot de passe stocké, sont nécessaires.');
if(seed.products.some(product => product.photo && !/^data:image\/(png|jpeg|webp);base64,/.test(product.photo))) throw new Error('Les photos de la démo doivent être incorporées au format data URI.');
if(/\bfetch\s*\(|^\s*import\s|serviceWorker\.register|navigator\.onLine/m.test(app)) throw new Error('Une dépendance au réseau ou un module subsiste dans la démonstration.');
new vm.Script(core,{filename:'demo-core.js'});
new vm.Script(reversals,{filename:'lib/reversals.js'});
new vm.Script(backups,{filename:'demo-backups.js'});
new vm.Script(browser,{filename:'demo-browser.js'});
new vm.Script(offline+'\n'+app,{filename:'demo-app.js'});
const css = read('public/style.css')+`\n.demo-banner { position:sticky; top:0; z-index:80; padding:9px 20px; display:flex; align-items:center; justify-content:center; gap:18px; background:#f0ecff; border-bottom:1px solid #e6ddfb; color:#8069a2; font:500 10px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }.demo-banner span { opacity:.72; font-weight:400; }.sidebar { top:34px; height:calc(100dvh - 34px); }.app-shell,.login-shell { min-height:calc(100vh - 34px); }@media(max-width:760px){.demo-banner{gap:6px;padding:8px 12px;font-size:9px;}.demo-banner span{display:none;}.sidebar{top:30px;height:calc(100dvh - 30px);}}@media print{.demo-banner{display:none!important;}}\n`;
const safeScript = source => source.replace(/<\/script/gi,'<\\/script');
const safeSeed = JSON.stringify(seed).replaceAll('<','\\u003c').replaceAll('\u2028','\\u2028').replaceAll('\u2029','\\u2029');
const html = `<!doctype html>\n<html lang="fr">\n<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#7153e8"><meta name="description" content="Démonstration locale et autonome de Comptoir. Données fictives conservées sur cet appareil."><title>Comptoir — Démonstration locale</title><style>${css.replace(/<\/style/gi,'<\\/style')}</style></head>\n<body><div class="demo-banner">Démonstration locale · données sur cet appareil <span>Comptes et rôles simulés</span></div><div id="app"><div class="loading-screen"><span class="loading-mark">C</span><p>Ouverture de votre comptoir…</p></div></div><div id="modal-root"></div><div id="toast-root" aria-live="polite" aria-atomic="true"></div><script id="comptoir-demo-seed" type="application/json">${safeSeed}</script><script>${safeScript(reversals)}</script><script>${safeScript(core)}</script><script>${safeScript(browser)}</script><script>${safeScript(offline+'\n'+app)}</script></body></html>\n`;
const target = path.join(root,'dist','Comptoir-demo.html');
fs.mkdirSync(path.dirname(target),{recursive:true});
const standalone = html.replace(`<script id="comptoir-demo-seed" type="application/json">${safeSeed}</script>`, `<script>window.ComptoirDemoSeed=${safeSeed};</script>`).replace(`<script>${safeScript(browser)}</script>`,`<script>${safeScript(backups)}</script><script>${safeScript(browser)}</script>`);
fs.writeFileSync(target+'.tmp',standalone);
fs.renameSync(target+'.tmp',target);
console.log('Démonstration autonome générée : dist/Comptoir-demo.html ('+Buffer.byteLength(standalone)+' octets).');
