(function browserTests() {
  const {test,expect}=require('@playwright/test');
  const {mkdtempSync,rmSync}=require('node:fs');
  const {tmpdir}=require('node:os');
  const path=require('node:path');
  const {StockService}=require('../../lib/business');
  const {createApp}=require('../../server');
  let service,server,base,uploadDir,errors;
  test.beforeEach(async({page})=>{
    service=new StockService({dbPath:':memory:',production:false});
    uploadDir=mkdtempSync(path.join(tmpdir(),'comptoir-browser-'));
    const app=createApp({service,uploadDir});
    server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
    base=`http://127.0.0.1:${server.address().port}`;
    errors=[];page.on('pageerror',error=>errors.push(error.message));
    page.on('console',message=>{if(message.type()==='warning'&&/^(Reprise de synchronisation|Envoi à reprendre)/.test(message.text())) console.log(message.text());});
    await page.goto(base);
  });
  test.afterEach(async({page})=>{
    await page.close();
    await new Promise(resolve=>{server.close(resolve);server.closeAllConnections();});
    service.close();rmSync(uploadDir,{recursive:true,force:true});
    expect(errors).toEqual([]);
  });
  async function login(page,role='admin') {
    await page.locator(`[data-demo="${role}"]`).click();
    await expect(page.getByRole('heading',{name:'Vue d’ensemble',exact:true})).toBeVisible();
    await expect(page.locator('#sync-state')).toHaveText('À jour');
  }
  const getState=async page=>(await page.request.get(base+'/api/state')).json();
  async function newOperation(page,type,productId,quantity,paid,contactId) {
    await page.getByRole('button',{name:'Nouvelle opération',exact:true}).click();
    await page.locator('[name=type]').selectOption(type);
    await page.locator('[name=lineProduct]').selectOption(productId);
    await page.locator('[name=lineQuantity]').fill(String(quantity));
    if(contactId)await page.locator('[name=contactId]').selectOption(contactId);
    if(paid!==undefined)await page.locator('[name=paid]').fill(String(paid));
    await page.getByRole('button',{name:'Valider l’opération',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  test('catalogue, stock fractionné, vente partielle, paiement, document et CSV',async({page},info)=>{
    await login(page);
    await expect(page.locator('.main')).toHaveCSS('grid-column-start','2');
    await page.screenshot({path:info.outputPath('dashboard.png'),fullPage:true});
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    await page.getByRole('textbox',{name:'Rechercher un produit'}).fill('riz');
    await expect(page.locator('tbody tr')).toHaveCount(1);
    await page.getByRole('textbox',{name:'Rechercher un produit'}).fill('');
    await page.getByRole('button',{name:'Ajouter un produit',exact:true}).click();
    await page.getByLabel('Nom du produit').fill('Café test UI');
    await page.getByLabel('Référence / SKU').fill('UI-CAFE');
    await page.getByLabel('Catégorie / dossier').fill('Épicerie / Café');
    await page.getByLabel('Prix d’achat (FCFA)').fill('100');
    await page.getByLabel('Prix de vente (FCFA)').fill('150');
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    const p=(await getState(page)).products.find(p=>p.sku==='UI-CAFE');
    expect(p).toBeTruthy();
    await page.getByRole('button',{name:'Mouvements',exact:true}).click();
    await newOperation(page,'purchase',p.id,10.5);
    let current=await getState(page);
    expect(current.stocks.find(s=>s.productId===p.id&&s.storeId==='store-centre').quantity).toBe(10.5);
    const customer=current.contacts.find(c=>c.type==='customer');
    await newOperation(page,'sale',p.id,2,100,customer.id);
    current=await getState(page);
    const sale=current.documents.find(d=>d.type==='sale'&&d.lines.some(l=>l.productId===p.id));
    expect(sale.total).toBe(300);expect(sale.paid).toBe(100);expect(sale.lines[0].purchaseCost).toBe(100);
    expect(current.stocks.find(s=>s.productId===p.id&&s.storeId==='store-centre').quantity).toBe(8.5);
    await page.getByRole('button',{name:'Voir '+sale.number,exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('Café test UI');
    await page.getByRole('button',{name:'Ajouter un paiement',exact:true}).click();
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    expect((await getState(page)).documents.find(d=>d.id===sale.id).paid).toBe(300);
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    const downloadPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Exporter',exact:true}).click();
    expect((await downloadPromise).suggestedFilename()).toMatch(/^catalogue-.*\.csv$/);
    await page.getByRole('button',{name:'Rapports & analyses',exact:true}).click();
    await expect(page.getByRole('heading',{name:'Rapports & analyses',exact:true})).toBeVisible();
    const docs=(await getState(page)).documents.filter(d=>d.type==='sale'&&d.storeId==='store-centre');
    const gross=docs.reduce((s,d)=>s+d.lines.reduce((sum,l)=>sum+Math.round(l.quantity*l.unitPrice)-Math.round(l.quantity*l.purchaseCost),0),0);
    const displayed=await page.locator('.metric-card').filter({hasText:'Bénéfice brut réalisé'}).locator('.metric-value').textContent();
    expect(Number(displayed.replace(/[^\d-]/g,''))).toBe(gross);
    await page.getByRole('button',{name:'Paramètres',exact:true}).click();
    await page.getByRole('checkbox',{name:'Mode sans prix'}).check();
    await page.getByRole('button',{name:'Enregistrer les préférences',exact:true}).click();
    await expect(page.locator('.no-price-banner')).toBeVisible();
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    await expect(page.getByRole('columnheader',{name:'Prix de vente'})).toHaveCount(0);
  });
  test('inventaire : sauvegarder les comptages puis valider les écarts',async({page})=>{
    await login(page);
    await page.getByRole('button',{name:'Inventaires',exact:true}).click();
    await page.getByRole('button',{name:'Nouvel inventaire',exact:true}).click();
    await page.getByLabel('Nom de la session').fill('Comptage du rayon test');
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    let current=await getState(page);
    const inv=current.inventories.find(i=>i.name==='Comptage du rayon test');
    await page.locator(`[data-inventory="${inv.id}"]`).click();
    for(let i=0;i<inv.lines.length;i++)await page.locator('.count-input').nth(i).fill(String(inv.lines[i].theoretical+(i===0?1:0)));
    await page.getByRole('button',{name:'Enregistrer le comptage',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.locator(`[data-inventory="${inv.id}"]`).click();
    await page.getByRole('button',{name:'Valider l’inventaire',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    current=await getState(page);
    expect(current.inventories.find(i=>i.id===inv.id).status).toBe('validated');
    expect(current.stocks.find(s=>s.productId===inv.lines[0].productId&&s.storeId===inv.storeId).quantity).toBe(inv.lines[0].theoretical+1);
  });
  test('hors ligne : cache après rechargement et commande synchronisée une seule fois',async({page,context})=>{
    await login(page);
    await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));});
    await context.setOffline(true);
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    await page.getByRole('button',{name:'Ajouter un produit',exact:true}).click();
    await page.getByLabel('Nom du produit').fill('Produit hors ligne');
    await page.getByLabel('Référence / SKU').fill('OFFLINE-001');
    await page.getByLabel('Catégorie / dossier').fill('Tests');
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('#sync-state')).toHaveText('Hors ligne');
    expect(service.all('products').filter(p=>p.sku==='OFFLINE-001')).toHaveLength(0);
    await page.reload();
    await expect(page.getByRole('heading',{name:'Vue d’ensemble',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    await expect(page.locator('tbody tr')).toHaveCount(10);
    await context.setOffline(false);
    await expect.poll(()=>service.all('products').filter(p=>p.sku==='OFFLINE-001').length,{timeout:12000}).toBe(1);
    await expect(page.locator('#sync-state')).toHaveText('À jour',{timeout:12000});
    await page.getByRole('button',{name:'À jour',exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('Toutes vos saisies sont synchronisées');
    expect(service.all('products').filter(p=>p.sku==='OFFLINE-001')).toHaveLength(1);
  });
  test('session expirée : conserver la saisie et la reprendre après reconnexion',async({page})=>{
    await login(page);
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    await page.getByRole('button',{name:'Ajouter un produit',exact:true}).click();
    await page.getByLabel('Nom du produit').fill('Produit session expirée');
    await page.getByLabel('Référence / SKU').fill('SESSION-001');
    await page.getByLabel('Catégorie / dossier').fill('Tests');
    service.db.exec('DELETE FROM sessions');
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
    await expect(page.locator('[data-demo="admin"]')).toBeVisible();
    expect(service.all('products').filter(p=>p.sku==='SESSION-001')).toHaveLength(0);
    await login(page);
    await expect.poll(()=>service.all('products').filter(p=>p.sku==='SESSION-001').length).toBe(1);
  });
  test('vente hors ligne rejetée : conflit visible et stock conservé',async({page,context})=>{
    await login(page);
    await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
    const before=await getState(page),p=before.products[0];
    const available=before.stocks.find(s=>s.productId===p.id&&s.storeId==='store-centre').quantity;
    await context.setOffline(true);
    await page.getByRole('button',{name:'Mouvements',exact:true}).click();
    await newOperation(page,'sale',p.id,available+1);
    expect(service.state(before.user).documents.length).toBe(before.documents.length);
    await context.setOffline(false);
    await expect(page.locator('#sync-state')).toHaveText('1 en attente',{timeout:12000});
    await page.locator('#sync-state').click();
    await expect(page.getByRole('dialog').locator('.form-error')).toContainText('Stock insuffisant');
    expect(service.state(before.user).stocks.find(s=>s.productId===p.id&&s.storeId==='store-centre').quantity).toBe(available);
    expect(service.state(before.user).documents.length).toBe(before.documents.length);
    await page.getByRole('button',{name:'Abandonner',exact:true}).click();
    await page.getByRole('button',{name:'Confirmer l’abandon',exact:true}).click();
    await expect(page.getByRole('dialog')).toContainText('Toutes vos saisies sont synchronisées');
  });
  test('mobile et rôles restreints : aucun coût achat ni validation agent',async({page},info)=>{
    await page.setViewportSize({width:390,height:844});
    await login(page,'cashier');
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.getByRole('button',{name:'Ouvrir le menu',exact:true}).click();
    await expect(page.getByRole('button',{name:'Inventaires',exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'Catalogue produits',exact:true}).click();
    await expect(page.getByRole('columnheader',{name:'Marge unitaire'})).toHaveCount(0);
    await expect(page.getByRole('button',{name:'Ajouter un produit',exact:true})).toHaveCount(0);
    const safe=await getState(page);expect(safe.products.every(p=>!Object.hasOwn(p,'purchasePrice'))).toBe(true);
    await page.screenshot({path:info.outputPath('mobile-catalogue.png'),fullPage:true});
    await page.getByRole('button',{name:'Ouvrir le menu',exact:true}).click();
    await page.getByRole('button',{name:'Se déconnecter',exact:true}).click();
    await login(page,'inventory');
    await page.getByRole('button',{name:'Nouvel inventaire',exact:true}).click();
    await page.getByLabel('Nom de la session').fill('Comptage agent');
    await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button',{name:'Ouvrir le menu',exact:true}).click();
    await page.getByRole('button',{name:'Inventaires',exact:true}).click();
    const inv=(await getState(page)).inventories.find(i=>i.name==='Comptage agent');
    await page.locator(`[data-inventory="${inv.id}"]`).click();
    await expect(page.getByRole('button',{name:'Valider l’inventaire',exact:true})).toHaveCount(0);
    await expect(page.getByRole('button',{name:'Enregistrer le comptage',exact:true})).toBeVisible();
    const state=await getState(page);expect(state.products.every(p=>!Object.hasOwn(p,'sellingPrice')&&!Object.hasOwn(p,'purchasePrice'))).toBe(true);
  });
})();
